name: Deploy SAM Application

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS access key from GitHub secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS secret key from GitHub secrets
          aws-region: eu-west-1  

      # Gå til mappen der template.yaml ligger
      - name: Change Directory to SAM App
        run: cd sam_lambda/had-imgGenerator

      - name: Build SAM application
        run: |
          cd sam_lambda/had-imgGenerator
          sam build --template template.yaml  # Bruk riktig sti for å bygge SAM-applikasjonen

      - name: Deploy SAM application
        run: |
          cd sam_lambda/had-imgGenerator
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name had-imgGenerator --capabilities CAPABILITY_IAM
