name: Publish Java SQS Client Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./java_sqs_client
        file: ./java_sqs_client/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/java-sqs-client:latest
          ${{ secrets.DOCKER_USERNAME }}/java-sqs-client:${{ github.sha }}

    - name: AWS CLI Configure
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region eu-west-1

    - name: Run Docker Container for Test
      run: |
        docker run -e SQS_QUEUE_URL="https://sqs.eu-west-1.amazonaws.com/244530008913/104-image-queue" \
        ${{ secrets.DOCKER_USERNAME }}/java-sqs-client:latest "Test Message"
