name: "terraform deploy"

on:
  push:
    branches:
      - main       # trigger workflow on push to main branch
      - '**'       # trigger workflow on push to any other branch
  pull_request:    # trigger workflow on pull requests

jobs:
  terraform:
    name: "terraform infrastructure deploy"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
      AWS_REGION: eu-west-1  

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: change to infra directory
        working-directory: ./infra
        run: pwd  # verify we are in the correct folder

      - name: set up terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false  

      - name: terraform init
        id: init
        working-directory: ./infra
        run: terraform init  # initialize terraform

      - name: terraform plan
        id: plan
        if: github.ref != 'refs/heads/main'  # only run terraform plan if not on main branch
        working-directory: ./infra
        run: terraform plan -no-color 

      - name: terraform apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # only apply if on main branch
        working-directory: ./infra
        run: terraform apply -auto-approve  
